name: Build Raincheck App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Backend dependencies
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
        cd ..

    # Frontend build
    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm install
        npm run build
        cd ..

    # Electron build
    - name: Build Electron App
      run: |
        cd electron
        npm install
        npx electron-builder --win --x64
        cd ..

    # Upload EXE as artifact
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: RainCheck-Windows
        path: electron/dist/*.exe


